remove ubuntu 3.3 for actions
poissonconsulting/chk pull request #111
Opened 2022-06-17 20:31 UTC by nadinehussein

only action failing is ubuntu 3.3

2022-06-17 22:14 UTC, joethorley requested changes
I think should also bump the version in the description file since we can't guarantee 3.3

```
Depends: 
    R (>= 3.3)
```

2022-06-17 22:18 UTC, nadinehussein commented
Bump it to 3.4? It already depends on 
```
Depends: 
    R (>= 3.3)
```

2022-06-17 22:22 UTC, joethorley commented
Yes I think we should set the DESCRIPTION to be >=3.4 since we can't guarantee that it works with 3.3 anymore

2022-06-18 00:04 UTC, joethorley approved these changes

2022-06-18 00:04 UTC, merged